# Grafana
grafana_url: "http://{{ inventory_hostname }}/grafana/"
grafana_users:
    default_theme: "light"

grafana_security:
    admin_user: admin
    admin_password: "{{ grafana_admin_pass }}"
    allow_embedding: "true"

grafana_auth:
    anonymous:
        enabled: "true"
        org_name: "Main org."
        org_role: "Viewer"

# These datasources will be automatically included into Grafana
grafana_image_storage:
  provider: local

grafana_environment:
  GF_PANELS_DISABLE_SANITIZE_HTML: 'true'

grafana_plugins:
  - grafana-worldmap-panel
  - grafana-piechart-panel
  - natel-discrete-panel

grafana_datasources:
 - name: Galaxy
   type: influxdb
   access: proxy
   url: http://127.0.0.1:8086
   isDefault: true
   version: 1
   editable: false
   database: telegraf
